CREATE TABLE CONTACTS
	(
	CONTACT_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY  CONSTRAINT CONTACT_PK PRIMARY KEY,
	CONTACT_FIRSTNAME VARCHAR(40) NOT NULL,
	CONTACT_LASTNAME VARCHAR(140) NOT NULL,
	CONTACT_PHONENUMBER VARCHAR(15) NOT NULL,
	CONTACT_ADDRESS VARCHAR(500),
	ADDRESS_BOOK_ID INT CONSTRAINT ADDRESS_BOOK_FK REFERENCES ADDRESS_BOOKS
);

insert into CONTACTS (CONTACT_FIRSTNAME, CONTACT_LASTNAME, CONTACT_PHONENUMBER, CONTACT_ADDRESS, ADDRESS_BOOK_ID) values('Clément', 'Serrano', '987654321', 'Paris', null)


DROP TABLE CONTACTS;